// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: modules/character/characterpb/character.proto

package characterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterListRequest_Regions int32

const (
	CharacterListRequest_ALL_REGION CharacterListRequest_Regions = 0
	CharacterListRequest_MONDSTAT   CharacterListRequest_Regions = 1
	CharacterListRequest_LIYUE      CharacterListRequest_Regions = 2
	CharacterListRequest_INAZUMA    CharacterListRequest_Regions = 3
)

// Enum value maps for CharacterListRequest_Regions.
var (
	CharacterListRequest_Regions_name = map[int32]string{
		0: "ALL_REGION",
		1: "MONDSTAT",
		2: "LIYUE",
		3: "INAZUMA",
	}
	CharacterListRequest_Regions_value = map[string]int32{
		"ALL_REGION": 0,
		"MONDSTAT":   1,
		"LIYUE":      2,
		"INAZUMA":    3,
	}
)

func (x CharacterListRequest_Regions) Enum() *CharacterListRequest_Regions {
	p := new(CharacterListRequest_Regions)
	*p = x
	return p
}

func (x CharacterListRequest_Regions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterListRequest_Regions) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[0].Descriptor()
}

func (CharacterListRequest_Regions) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[0]
}

func (x CharacterListRequest_Regions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterListRequest_Regions.Descriptor instead.
func (CharacterListRequest_Regions) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{0, 0}
}

type CharacterListRequest_Weapons int32

const (
	CharacterListRequest_ALL_WEAPON CharacterListRequest_Weapons = 0
	CharacterListRequest_SWORD      CharacterListRequest_Weapons = 1
	CharacterListRequest_CLAYMORE   CharacterListRequest_Weapons = 2
	CharacterListRequest_BOW        CharacterListRequest_Weapons = 3
	CharacterListRequest_POLEARM    CharacterListRequest_Weapons = 4
	CharacterListRequest_CATALYST   CharacterListRequest_Weapons = 5
)

// Enum value maps for CharacterListRequest_Weapons.
var (
	CharacterListRequest_Weapons_name = map[int32]string{
		0: "ALL_WEAPON",
		1: "SWORD",
		2: "CLAYMORE",
		3: "BOW",
		4: "POLEARM",
		5: "CATALYST",
	}
	CharacterListRequest_Weapons_value = map[string]int32{
		"ALL_WEAPON": 0,
		"SWORD":      1,
		"CLAYMORE":   2,
		"BOW":        3,
		"POLEARM":    4,
		"CATALYST":   5,
	}
)

func (x CharacterListRequest_Weapons) Enum() *CharacterListRequest_Weapons {
	p := new(CharacterListRequest_Weapons)
	*p = x
	return p
}

func (x CharacterListRequest_Weapons) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterListRequest_Weapons) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[1].Descriptor()
}

func (CharacterListRequest_Weapons) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[1]
}

func (x CharacterListRequest_Weapons) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterListRequest_Weapons.Descriptor instead.
func (CharacterListRequest_Weapons) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{0, 1}
}

type CharacterListRequest_Visions int32

const (
	CharacterListRequest_ALL_VISION CharacterListRequest_Visions = 0
	CharacterListRequest_PYRO       CharacterListRequest_Visions = 1
	CharacterListRequest_CYRO       CharacterListRequest_Visions = 2
	CharacterListRequest_ELECTRO    CharacterListRequest_Visions = 3
	CharacterListRequest_HYDRO      CharacterListRequest_Visions = 4
	CharacterListRequest_ANEMO      CharacterListRequest_Visions = 5
	CharacterListRequest_GEO        CharacterListRequest_Visions = 6
	CharacterListRequest_DENDRO     CharacterListRequest_Visions = 7
)

// Enum value maps for CharacterListRequest_Visions.
var (
	CharacterListRequest_Visions_name = map[int32]string{
		0: "ALL_VISION",
		1: "PYRO",
		2: "CYRO",
		3: "ELECTRO",
		4: "HYDRO",
		5: "ANEMO",
		6: "GEO",
		7: "DENDRO",
	}
	CharacterListRequest_Visions_value = map[string]int32{
		"ALL_VISION": 0,
		"PYRO":       1,
		"CYRO":       2,
		"ELECTRO":    3,
		"HYDRO":      4,
		"ANEMO":      5,
		"GEO":        6,
		"DENDRO":     7,
	}
)

func (x CharacterListRequest_Visions) Enum() *CharacterListRequest_Visions {
	p := new(CharacterListRequest_Visions)
	*p = x
	return p
}

func (x CharacterListRequest_Visions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterListRequest_Visions) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[2].Descriptor()
}

func (CharacterListRequest_Visions) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[2]
}

func (x CharacterListRequest_Visions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterListRequest_Visions.Descriptor instead.
func (CharacterListRequest_Visions) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{0, 2}
}

type CharacterListResponse_Visions int32

const (
	CharacterListResponse_ALL_VISION CharacterListResponse_Visions = 0
	CharacterListResponse_PYRO       CharacterListResponse_Visions = 1
	CharacterListResponse_CYRO       CharacterListResponse_Visions = 2
	CharacterListResponse_ELECTRO    CharacterListResponse_Visions = 3
	CharacterListResponse_HYDRO      CharacterListResponse_Visions = 4
	CharacterListResponse_ANEMO      CharacterListResponse_Visions = 5
	CharacterListResponse_GEO        CharacterListResponse_Visions = 6
	CharacterListResponse_DENDRO     CharacterListResponse_Visions = 7
)

// Enum value maps for CharacterListResponse_Visions.
var (
	CharacterListResponse_Visions_name = map[int32]string{
		0: "ALL_VISION",
		1: "PYRO",
		2: "CYRO",
		3: "ELECTRO",
		4: "HYDRO",
		5: "ANEMO",
		6: "GEO",
		7: "DENDRO",
	}
	CharacterListResponse_Visions_value = map[string]int32{
		"ALL_VISION": 0,
		"PYRO":       1,
		"CYRO":       2,
		"ELECTRO":    3,
		"HYDRO":      4,
		"ANEMO":      5,
		"GEO":        6,
		"DENDRO":     7,
	}
)

func (x CharacterListResponse_Visions) Enum() *CharacterListResponse_Visions {
	p := new(CharacterListResponse_Visions)
	*p = x
	return p
}

func (x CharacterListResponse_Visions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterListResponse_Visions) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[3].Descriptor()
}

func (CharacterListResponse_Visions) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[3]
}

func (x CharacterListResponse_Visions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterListResponse_Visions.Descriptor instead.
func (CharacterListResponse_Visions) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{1, 0}
}

type CharacterListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   *string                       `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Region *CharacterListRequest_Regions `protobuf:"varint,2,opt,name=region,proto3,enum=character.CharacterListRequest_Regions,oneof" json:"region,omitempty"`
	Rarity *int32                        `protobuf:"varint,3,opt,name=rarity,proto3,oneof" json:"rarity,omitempty"`
	Weapon *CharacterListRequest_Weapons `protobuf:"varint,4,opt,name=Weapon,proto3,enum=character.CharacterListRequest_Weapons,oneof" json:"Weapon,omitempty"`
	Vision *CharacterListRequest_Visions `protobuf:"varint,5,opt,name=Vision,proto3,enum=character.CharacterListRequest_Visions,oneof" json:"Vision,omitempty"`
}

func (x *CharacterListRequest) Reset() {
	*x = CharacterListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_character_characterpb_character_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterListRequest) ProtoMessage() {}

func (x *CharacterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_character_characterpb_character_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterListRequest.ProtoReflect.Descriptor instead.
func (*CharacterListRequest) Descriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CharacterListRequest) GetRegion() CharacterListRequest_Regions {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return CharacterListRequest_ALL_REGION
}

func (x *CharacterListRequest) GetRarity() int32 {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return 0
}

func (x *CharacterListRequest) GetWeapon() CharacterListRequest_Weapons {
	if x != nil && x.Weapon != nil {
		return *x.Weapon
	}
	return CharacterListRequest_ALL_WEAPON
}

func (x *CharacterListRequest) GetVision() CharacterListRequest_Visions {
	if x != nil && x.Vision != nil {
		return *x.Vision
	}
	return CharacterListRequest_ALL_VISION
}

type CharacterListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity   int32                         `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Vision   CharacterListResponse_Visions `protobuf:"varint,4,opt,name=vision,proto3,enum=character.CharacterListResponse_Visions" json:"vision,omitempty"`
	ImageUrl string                        `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *CharacterListResponse) Reset() {
	*x = CharacterListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_character_characterpb_character_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterListResponse) ProtoMessage() {}

func (x *CharacterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_character_characterpb_character_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterListResponse.ProtoReflect.Descriptor instead.
func (*CharacterListResponse) Descriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterListResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CharacterListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterListResponse) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *CharacterListResponse) GetVision() CharacterListResponse_Visions {
	if x != nil {
		return x.Vision
	}
	return CharacterListResponse_ALL_VISION
}

func (x *CharacterListResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_modules_character_characterpb_character_proto protoreflect.FileDescriptor

var file_modules_character_characterpb_character_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2f,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0xd3, 0x04, 0x0a, 0x14, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x44, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x01, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x02, 0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x44, 0x0a, 0x06, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x27, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x48, 0x03, 0x52, 0x06, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x44, 0x0a, 0x06, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x04,
	0x52, 0x06, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x22, 0x3f, 0x0a, 0x07, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x45,
	0x47, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x4e, 0x44, 0x53, 0x54,
	0x41, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49, 0x59, 0x55, 0x45, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x41, 0x5a, 0x55, 0x4d, 0x41, 0x10, 0x03, 0x22, 0x56, 0x0a, 0x07,
	0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x57,
	0x45, 0x41, 0x50, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x57, 0x4f, 0x52, 0x44,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4c, 0x41, 0x59, 0x4d, 0x4f, 0x52, 0x45, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x42, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x4c,
	0x45, 0x41, 0x52, 0x4d, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x54, 0x41, 0x4c, 0x59,
	0x53, 0x54, 0x10, 0x05, 0x22, 0x65, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x59, 0x52, 0x4f, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x59, 0x52,
	0x4f, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x52, 0x4f, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x59, 0x44, 0x52, 0x4f, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x4e, 0x45, 0x4d, 0x4f, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x4f, 0x10, 0x06, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4e, 0x44, 0x52, 0x4f, 0x10, 0x07, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x57,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x98, 0x02, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x06, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x06, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x22, 0x65, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x59, 0x52, 0x4f, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x59, 0x52,
	0x4f, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x52, 0x4f, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x59, 0x44, 0x52, 0x4f, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x4e, 0x45, 0x4d, 0x4f, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x4f, 0x10, 0x06, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4e, 0x44, 0x52, 0x4f, 0x10, 0x07, 0x32, 0x6a, 0x0a, 0x14, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x2e, 0x2f, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2f, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_modules_character_characterpb_character_proto_rawDescOnce sync.Once
	file_modules_character_characterpb_character_proto_rawDescData = file_modules_character_characterpb_character_proto_rawDesc
)

func file_modules_character_characterpb_character_proto_rawDescGZIP() []byte {
	file_modules_character_characterpb_character_proto_rawDescOnce.Do(func() {
		file_modules_character_characterpb_character_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_character_characterpb_character_proto_rawDescData)
	})
	return file_modules_character_characterpb_character_proto_rawDescData
}

var file_modules_character_characterpb_character_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_modules_character_characterpb_character_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_character_characterpb_character_proto_goTypes = []interface{}{
	(CharacterListRequest_Regions)(0),  // 0: character.CharacterListRequest.Regions
	(CharacterListRequest_Weapons)(0),  // 1: character.CharacterListRequest.Weapons
	(CharacterListRequest_Visions)(0),  // 2: character.CharacterListRequest.Visions
	(CharacterListResponse_Visions)(0), // 3: character.CharacterListResponse.Visions
	(*CharacterListRequest)(nil),       // 4: character.CharacterListRequest
	(*CharacterListResponse)(nil),      // 5: character.CharacterListResponse
}
var file_modules_character_characterpb_character_proto_depIdxs = []int32{
	0, // 0: character.CharacterListRequest.region:type_name -> character.CharacterListRequest.Regions
	1, // 1: character.CharacterListRequest.Weapon:type_name -> character.CharacterListRequest.Weapons
	2, // 2: character.CharacterListRequest.Vision:type_name -> character.CharacterListRequest.Visions
	3, // 3: character.CharacterListResponse.vision:type_name -> character.CharacterListResponse.Visions
	4, // 4: character.CharacterListService.CharacterList:input_type -> character.CharacterListRequest
	5, // 5: character.CharacterListService.CharacterList:output_type -> character.CharacterListResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_modules_character_characterpb_character_proto_init() }
func file_modules_character_characterpb_character_proto_init() {
	if File_modules_character_characterpb_character_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_character_characterpb_character_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_character_characterpb_character_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_modules_character_characterpb_character_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_character_characterpb_character_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_character_characterpb_character_proto_goTypes,
		DependencyIndexes: file_modules_character_characterpb_character_proto_depIdxs,
		EnumInfos:         file_modules_character_characterpb_character_proto_enumTypes,
		MessageInfos:      file_modules_character_characterpb_character_proto_msgTypes,
	}.Build()
	File_modules_character_characterpb_character_proto = out.File
	file_modules_character_characterpb_character_proto_rawDesc = nil
	file_modules_character_characterpb_character_proto_goTypes = nil
	file_modules_character_characterpb_character_proto_depIdxs = nil
}
