// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: modules/character/characterpb/character.proto

package characterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//global ENUM
type WeaponTypes int32

const (
	WeaponTypes_ALL_WEAPON WeaponTypes = 0
	WeaponTypes_CLAYMORE   WeaponTypes = 1
	WeaponTypes_SWORD      WeaponTypes = 2
	WeaponTypes_BOW        WeaponTypes = 3
	WeaponTypes_POLEARM    WeaponTypes = 4
	WeaponTypes_CATALYST   WeaponTypes = 5
)

// Enum value maps for WeaponTypes.
var (
	WeaponTypes_name = map[int32]string{
		0: "ALL_WEAPON",
		1: "CLAYMORE",
		2: "SWORD",
		3: "BOW",
		4: "POLEARM",
		5: "CATALYST",
	}
	WeaponTypes_value = map[string]int32{
		"ALL_WEAPON": 0,
		"CLAYMORE":   1,
		"SWORD":      2,
		"BOW":        3,
		"POLEARM":    4,
		"CATALYST":   5,
	}
)

func (x WeaponTypes) Enum() *WeaponTypes {
	p := new(WeaponTypes)
	*p = x
	return p
}

func (x WeaponTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeaponTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[0].Descriptor()
}

func (WeaponTypes) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[0]
}

func (x WeaponTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeaponTypes.Descriptor instead.
func (WeaponTypes) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{0}
}

type Regions int32

const (
	Regions_ALL_REGION Regions = 0
	Regions_MONDSTADT  Regions = 1
	Regions_LIYUE      Regions = 2
	Regions_INAZUMA    Regions = 3
)

// Enum value maps for Regions.
var (
	Regions_name = map[int32]string{
		0: "ALL_REGION",
		1: "MONDSTADT",
		2: "LIYUE",
		3: "INAZUMA",
	}
	Regions_value = map[string]int32{
		"ALL_REGION": 0,
		"MONDSTADT":  1,
		"LIYUE":      2,
		"INAZUMA":    3,
	}
)

func (x Regions) Enum() *Regions {
	p := new(Regions)
	*p = x
	return p
}

func (x Regions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Regions) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[1].Descriptor()
}

func (Regions) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[1]
}

func (x Regions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Regions.Descriptor instead.
func (Regions) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{1}
}

type Visions int32

const (
	Visions_ALL_VISION Visions = 0
	Visions_PYRO       Visions = 1
	Visions_CYRO       Visions = 2
	Visions_HYDRO      Visions = 3
	Visions_ANEMO      Visions = 4
	Visions_ELECTRO    Visions = 5
	Visions_GEO        Visions = 6
	Visions_DENDRO     Visions = 7
)

// Enum value maps for Visions.
var (
	Visions_name = map[int32]string{
		0: "ALL_VISION",
		1: "PYRO",
		2: "CYRO",
		3: "HYDRO",
		4: "ANEMO",
		5: "ELECTRO",
		6: "GEO",
		7: "DENDRO",
	}
	Visions_value = map[string]int32{
		"ALL_VISION": 0,
		"PYRO":       1,
		"CYRO":       2,
		"HYDRO":      3,
		"ANEMO":      4,
		"ELECTRO":    5,
		"GEO":        6,
		"DENDRO":     7,
	}
)

func (x Visions) Enum() *Visions {
	p := new(Visions)
	*p = x
	return p
}

func (x Visions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visions) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[2].Descriptor()
}

func (Visions) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[2]
}

func (x Visions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visions.Descriptor instead.
func (Visions) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{2}
}

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_character_characterpb_character_proto_enumTypes[3].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_modules_character_characterpb_character_proto_enumTypes[3]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{3}
}

type CharacterListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       *string      `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Region     *Regions     `protobuf:"varint,2,opt,name=region,proto3,enum=character.Regions,oneof" json:"region,omitempty"`
	Rarity     *int32       `protobuf:"varint,3,opt,name=rarity,proto3,oneof" json:"rarity,omitempty"`
	WeaponType *WeaponTypes `protobuf:"varint,4,opt,name=WeaponType,proto3,enum=character.WeaponTypes,oneof" json:"WeaponType,omitempty"`
	Vision     *Visions     `protobuf:"varint,5,opt,name=Vision,proto3,enum=character.Visions,oneof" json:"Vision,omitempty"`
}

func (x *CharacterListRequest) Reset() {
	*x = CharacterListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_character_characterpb_character_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterListRequest) ProtoMessage() {}

func (x *CharacterListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_character_characterpb_character_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterListRequest.ProtoReflect.Descriptor instead.
func (*CharacterListRequest) Descriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CharacterListRequest) GetRegion() Regions {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return Regions_ALL_REGION
}

func (x *CharacterListRequest) GetRarity() int32 {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return 0
}

func (x *CharacterListRequest) GetWeaponType() WeaponTypes {
	if x != nil && x.WeaponType != nil {
		return *x.WeaponType
	}
	return WeaponTypes_ALL_WEAPON
}

func (x *CharacterListRequest) GetVision() Visions {
	if x != nil && x.Vision != nil {
		return *x.Vision
	}
	return Visions_ALL_VISION
}

type CharacterListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity   int32   `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Vision   Visions `protobuf:"varint,4,opt,name=vision,proto3,enum=character.Visions" json:"vision,omitempty"`
	ImageUrl string  `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Gender   Gender  `protobuf:"varint,6,opt,name=gender,proto3,enum=character.Gender" json:"gender,omitempty"`
}

func (x *CharacterListResponse) Reset() {
	*x = CharacterListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_character_characterpb_character_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterListResponse) ProtoMessage() {}

func (x *CharacterListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_character_characterpb_character_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterListResponse.ProtoReflect.Descriptor instead.
func (*CharacterListResponse) Descriptor() ([]byte, []int) {
	return file_modules_character_characterpb_character_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterListResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CharacterListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterListResponse) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *CharacterListResponse) GetVision() Visions {
	if x != nil {
		return x.Vision
	}
	return Visions_ALL_VISION
}

func (x *CharacterListResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CharacterListResponse) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

var File_modules_character_characterpb_character_proto protoreflect.FileDescriptor

var file_modules_character_characterpb_character_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2f,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0xa4, 0x02, 0x0a, 0x14, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73,
	0x48, 0x01, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52,
	0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a, 0x0a, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x61, 0x70, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x48, 0x03, 0x52, 0x0a, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x06, 0x56, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x04, 0x52, 0x06, 0x56,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x56, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x29, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2a, 0x5a, 0x0a, 0x0b, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c,
	0x5f, 0x57, 0x45, 0x41, 0x50, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4c, 0x41,
	0x59, 0x4d, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x57, 0x4f, 0x52, 0x44,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x4f, 0x4c, 0x45, 0x41, 0x52, 0x4d, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x54, 0x41,
	0x4c, 0x59, 0x53, 0x54, 0x10, 0x05, 0x2a, 0x40, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f, 0x4e, 0x44, 0x53, 0x54, 0x41, 0x44, 0x54, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49, 0x59, 0x55, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x41, 0x5a, 0x55, 0x4d, 0x41, 0x10, 0x03, 0x2a, 0x65, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x56, 0x49, 0x53, 0x49, 0x4f,
	0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x59, 0x52, 0x4f, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x43, 0x59, 0x52, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x59, 0x44, 0x52, 0x4f,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4e, 0x45, 0x4d, 0x4f, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x52, 0x4f, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45,
	0x4f, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4e, 0x44, 0x52, 0x4f, 0x10, 0x07, 0x2a,
	0x1e, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x32,
	0x6a, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x2e,
	0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_character_characterpb_character_proto_rawDescOnce sync.Once
	file_modules_character_characterpb_character_proto_rawDescData = file_modules_character_characterpb_character_proto_rawDesc
)

func file_modules_character_characterpb_character_proto_rawDescGZIP() []byte {
	file_modules_character_characterpb_character_proto_rawDescOnce.Do(func() {
		file_modules_character_characterpb_character_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_character_characterpb_character_proto_rawDescData)
	})
	return file_modules_character_characterpb_character_proto_rawDescData
}

var file_modules_character_characterpb_character_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_modules_character_characterpb_character_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_character_characterpb_character_proto_goTypes = []interface{}{
	(WeaponTypes)(0),              // 0: character.WeaponTypes
	(Regions)(0),                  // 1: character.Regions
	(Visions)(0),                  // 2: character.Visions
	(Gender)(0),                   // 3: character.Gender
	(*CharacterListRequest)(nil),  // 4: character.CharacterListRequest
	(*CharacterListResponse)(nil), // 5: character.CharacterListResponse
}
var file_modules_character_characterpb_character_proto_depIdxs = []int32{
	1, // 0: character.CharacterListRequest.region:type_name -> character.Regions
	0, // 1: character.CharacterListRequest.WeaponType:type_name -> character.WeaponTypes
	2, // 2: character.CharacterListRequest.Vision:type_name -> character.Visions
	2, // 3: character.CharacterListResponse.vision:type_name -> character.Visions
	3, // 4: character.CharacterListResponse.gender:type_name -> character.Gender
	4, // 5: character.CharacterListService.CharacterList:input_type -> character.CharacterListRequest
	5, // 6: character.CharacterListService.CharacterList:output_type -> character.CharacterListResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_modules_character_characterpb_character_proto_init() }
func file_modules_character_characterpb_character_proto_init() {
	if File_modules_character_characterpb_character_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_character_characterpb_character_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_character_characterpb_character_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_modules_character_characterpb_character_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_character_characterpb_character_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_character_characterpb_character_proto_goTypes,
		DependencyIndexes: file_modules_character_characterpb_character_proto_depIdxs,
		EnumInfos:         file_modules_character_characterpb_character_proto_enumTypes,
		MessageInfos:      file_modules_character_characterpb_character_proto_msgTypes,
	}.Build()
	File_modules_character_characterpb_character_proto = out.File
	file_modules_character_characterpb_character_proto_rawDesc = nil
	file_modules_character_characterpb_character_proto_goTypes = nil
	file_modules_character_characterpb_character_proto_depIdxs = nil
}
